# Generated by Django 5.0.6 on 2024-06-20 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Забронорованная дата')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_db.flat', verbose_name='Квартира')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Арендатор')),
            ],
            options={
                'unique_together': {('flat', 'date')},
            },
        ),
    ]
