# Generated by Django 5.0.6 on 2024-06-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_db', '0002_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='desc',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='flat',
            name='path',
            field=models.CharField(max_length=255, null=True, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='flat',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Слоган'),
        ),
    ]
