# Generated by Django 5.0.6 on 2024-07-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_db', '0003_flat_desc_flat_path_flat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='currency',
            field=models.CharField(default='USD', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена за ночь'),
        ),
    ]
